baseurl = "https://prashantkhurana.github.io/"
title = "Prashant Khurana"
theme = "hugo-theme-vec"
languageCode = "en-us"
paginate = 10
disqusShortname = ""
googleAnalytics = "UA-106192187-1"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "blog"
    weight = 1
    url = "/blog"
  [[menu.main]]
    name = "resume"
    weight = 2
    url = "/pdf/cv.pdf"
  [[menu.main]]
    name = "presentations"
    weight = 3
    url = "/presentations"

[params]
  Keywords = "key, 关键字, キーワード"
  Description = "There are some words to describe your site"
  Avatar = "img/me.jpg"
  SelfIntro = "Software engineer @ Dstillery, NYC"
  Email = "prashant@prashantkhurana.com"

  GithubID = "prashantkhurana"
  TwitterID = "prashantgolu"
  LinkedInID = "praskhurana"
  custom_css = ["css/custom.css"]