baseURL = "http://example.com/"
languageCode = "en-us"
title = "Prashant Khurana"
theme = "minimal"
pluralizelisttitles = false

[params]
    author = "Prashant Khurana"
    description = "Software engineer @ Dstillery, NYC"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "" # should match the name on Google Fonts!
    highlight = true
    highlightLanguages = []
    Avatar = "img/me.jpg"
    highlightStyle = ""

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/presentations/"
    name = "Presentations"
    weight = 3
#[[menu.main]]
 #   url = "/pdf/cv.pdf"
  #  name = "Resume"
   # weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "/mail"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/prashantkhurana/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/praskhurana/"
    name = "linkedin"
    weight = 3
